### ISSUE TITLE
Cursor moves on autosave

### ISSUE THREAD

**Issue by jakuta-tech** [factionsecurity/faction#17]
Hey thanks for the report generator. I built the latest image and when you type in any of the text boxes, the autosave seems to kick in and the cursor automatically jumps to the beginning of the line whilst typing.  Tried on multiple builds, Chrome, Firefox and all the same behavior.  
![image](https://github.com/factionsecurity/faction/assets/4783832/b788b1b2-4cbc-4482-ba7d-28166b87e938)

I had a further look and it appears it might be related to SunEditor

https://github.com/JiHong88/suneditor/issues/1307

https://github.com/JiHong88/suneditor/issues/1348

**Comment by summitt** [comment]
Thanks for reporting. I've been able to recreate ths issue. Will work on a fix and let you know when its done

**Comment by summitt** [comment]
Hey @jakuta-tech , This issue should be mitigated. I created a new release (1.1.18). You should be able to pull down the latest war file and run it. Make sure to clear the browser cache so your no running the old javascript. 

If you are still seeing the same issue and you are building off of main using maven then it should pull down the lastest javascript but you may need to rebuild the scripts with npm. You can do this as follows. 

```
cd WebContent
npm install
npm run build
```
I'm using npm version 6.14.4 and node v14.0.0
