### ISSUE TITLE
Logout on Assessments Page

### ISSUE THREAD

**Issue by SurajitCh10** [factionsecurity/faction#25]
Whenever I try to visit any assessments page, it shows session expired message.
<img width="941" alt="Screenshot 2024-02-05 104528" src="https://github.com/factionsecurity/faction/assets/72316799/237f8e91-83cb-4ae7-b382-1b9e72e24b3a">

**Comment by summitt** [comment]
Are you using our managed solution or running it on your own?
If running on your own are there any errors in the console? 
By chance are you running two instances of tomcat behind a load balancer?

**Comment by SurajitCh10** [comment]
I'm running it on my own. 
There are no errors in console , /portal/CheckLocks returning session expired message
There is only single instance of tomcat.
![image](https://github.com/factionsecurity/faction/assets/72316799/6c9da59c-a34b-48a1-be07-642c9b90296a)

**Comment by summitt** [comment]
@SurajitCh10 Thanks for reporting. I was able to replicate the issue. It was related to incorrect permissions being set up on the Assessment. A fix will be released shortly.

**Comment by summitt** [comment]
This should now be fixed in #27 . Let me know if you still experience the issue

**Comment by SurajitCh10** [comment]
@summitt I have checked and its fixed now.
