### ISSUE TITLE
Unable to Deploy on tomcat showing error as Application at path /faction could not be started 

### ISSUE THREAD

**Issue by Vishwa20241** [factionsecurity/faction#26]
Hi 

Im unable to deploy the war file directly on tomcat server as it i throwing the error Application at path /faction could not be started  ANy suggestions would be greatly appreciated

**Comment by Vishwa20241** [comment]
using tomcat 9

**Comment by summitt** [comment]
It needs read permissions to `/opt/faction/modules`. This is to support extending Faction.  It does not need to have anything in the folder for now but needs access to see if it's extended in any way. Let me know if adding this folder fixes your issue.

**Comment by summitt** [comment]
@Vishwa20241 If you are still having issues, try release 1.1.26. We are starting to remove any dependencies on the file system. Hopefully, this will fix your issue.
