### ISSUE TITLE
Instances not starting up

### ISSUE THREAD

**Issue by mskca** [factionsecurity/faction#4]
Hello, i am trying to test the software, but i cant initiate any instance.

First i tried to self-host with docker-compose, but i am getting a 404 error page on startup

Then i tried two types of licenses, but the instances do not startup and also show as 404 error

[[redacted screenshot]]

![image](https://github.com/factionsecurity/faction/assets/106720473/06762c01-ce62-4cf7-bdd8-16160fa8440c)

**Comment by summitt** [comment]
Hey thanks for reporting the issue. Sorry, it took me a bit to see you posted this. The issue is now mitigated and your instance is now live.

**Comment by summitt** [comment]
Closing issue as it's fixed in the most recent release.
