### ISSUE TITLE
Unable to retrieve assessment details

### ISSUE THREAD

**Issue by S-Velayutham** [factionsecurity/faction#53]
Hi Team,

Unable to retrieve the details, Am i going wrong anywhere . Kindly look into the screenshot & please advice 
<img width="343" alt="Screenshot 2024-03-28 103347" src="https://github.com/factionsecurity/faction/assets/104140326/0dfaab91-8a65-471f-b1c5-9a160fde7beb">

**Comment by summitt** [comment]
I really need to write better documentation here... 

You need to add the path of the API here. If (for example) you access Faction at  http://myserver.com:8080/ then the API is at http://myserver.com:8080/api. 

You may have deployed faction somewhere other than ROOT on Tomcat. In that case, if you access Faction at http://myserver.com:8080/myfaction/ then the api will be at https://myserver.com:8080/myfaction/api

Hope this helps.

**Comment by S-Velayutham** [comment]
Thank you

**Comment by S-Velayutham** [comment]
Thank you
