### ISSUE TITLE
Unable to change Findings

### ISSUE THREAD

**Issue by cv3tomuzika** [factionsecurity/faction#54]
Version 1.2.2, self-hosted, VMware.
In order to change the name of the selected finding, you need to click on `+New Vulnerability`, which adds a new finding.
Deleting or changing Overall Severity of the findings just doesn't work.
![image](https://github.com/factionsecurity/faction/assets/165099525/42c59a5e-f7ae-4e1d-9e66-0d1d0fa61a59)
![image](https://github.com/factionsecurity/faction/assets/165099525/d4f7b294-b80c-4ad9-b75c-eea17f58f02d)

HAR-file sent to email.

**Comment by summitt** [comment]
Thanks for sending the HAR. I'll take a look. I'm guessing another locale issue.

**Comment by summitt** [comment]
@cv3tomuzika Just release 1.2.3. Take a look and see if this fixes your issue.

**Comment by summitt** [comment]
Assuming this issue is closed. Feel free to reopen if its not
