### ISSUE TITLE
Document generation does not replace in header / footer templates

### ISSUE THREAD

**Issue by mvarendorff2** [factionsecurity/faction#64]
When using a document with header and footer templates, the substitution of variables like `${today}` does not seem to affect them.

Example footer in Word edit view:

![grafik](https://github.com/user-attachments/assets/b557e88f-f81f-4280-8d0b-254032b895cd)

Output in the generated document:

![grafik](https://github.com/user-attachments/assets/1ac05887-a178-4ea8-8879-dacd7a368ce2)

**Comment by summitt** [comment]
Thanks for reporting. We'll look into it.

**Comment by summitt** [comment]
This should be fixed now in 1.3.28
https://github.com/factionsecurity/faction/releases/tag/1.3.28

**Comment by mvarendorff2** [comment]
Yes, it is! Thank you so much ❤️
