### ISSUE TITLE
Vulnerability created via API is empty

### ISSUE THREAD

**Issue by ptrac3** [factionsecurity/faction#68]
I hope this is the right place to ask and, if by any chance, you recognise I have missed something and/or this is not the right place to ask feel free to delete this message.
I was trying to add vulnerabilities the available documentation at https://docs.factionsecurity.com/Importing%20Your%20Vulnerability%20Templates%20Via%20the%20API/ by using JSON with the following payload:

 curl -X 'POST' \
  'http://localhost:8080/api/vulnerabilities/default' \
  -H 'accept: application/json' \
  -H 'FACTION-API-KEY: API_KEY' \
  -H 'Content-Type: application/json' \
  -d '[
  {
    "Name": "This_is_a_test",
    "CategoryName": "Unvalidated Input",
    "Description": "Description",
    "Recommendation": "Recommendation",
    "LikelihoodId": 4,
    "ImpactId": 4,
    "SeverityId": 4,
    "Active": true
  }
]'
This request will result in the creation of the vulnerability but, as you can see from the screenshot, it will not include any of the details provided. Did I miss something?
I also tried changing the name of the parameters (in the web UI for example the Likelihood parameters is "Likelyhood") but it did not yield any successful results.
![image](https://github.com/user-attachments/assets/c2d15350-bbf4-4681-a25c-169d98b13078)
Also, there seems to be something weird happening since the Impact and Likelihood are correct while the overall Severity is not. In addition, no information regarding the issue description or recommendation is added.

**Comment by summitt** [comment]
I'll take a look this week.

**Comment by ptrac3** [comment]
> I'll take a look this week.

Thanks, no rush! In the meantime I am using MongoDB and some scripting to directly update the db.

<unrelated>I know it is not related to this issue but I have noticed that in the latest release the App Store from the menu seems missing and I am experiencing issues when trying to schedule something (I get Error 500 when trying to do so, I have noticed the API call to getAssessments endpoints via chrome Console) as it does not seem to be possible to add an assessor. I am not sure whether these are just my problems or not..</unrelated>

**Comment by ptrac3** [comment]
Hi @summitt did you by any chance had the time to have a look at that?

**Comment by summitt** [comment]
I've been a bit backlogged on other projects at the moment. I hope to get to is early next week.

**Comment by summitt** [comment]
@ptrac3 Newest release fixes this issue. Take note that we made updates to our password hashing as part of other updates we have been making,  which means you'll need to reset your password in the system after you upgrade.
