### ISSUE TITLE
Stored XSS in Vulnerability Title

### ISSUE THREAD

**Issue by GPUkiller** [factionsecurity/faction#71]
1) Add XSS Payload in the vulnerability title using a pentester account for example who can only insert vulnerabilities:
![image](https://github.com/user-attachments/assets/1dc606a1-c597-4b05-b5e1-c3511e655ddf)
2) Now when the Report Creator Admin or Reviewer visits the Audit page of the project, the XSS payload will be triggered
![image](https://github.com/user-attachments/assets/e2884ef7-3291-4397-ba53-6053a8b609de)
Even removing the vulnerability will not remove the payload as it is on the audit page.

**Comment by summitt** [comment]
Thanks for reporting. We'll mitigate it.
